version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service-new
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=your_super_secret_key
      - DATABASE_URL=sqlite:///app.db  # SQLite connection string
    volumes:
      - ./auth-service:/app  # Ensure the app can read/write to the DB file
    networks:
      - app-network

  password-service:
    build:
      context: ./password-service
    container_name: password-service-new
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - JWT_SECRET_KEY=your_super_secret_key
      - DATABASE_URL=sqlite:///app.db  # SQLite connection string
    volumes:
      - ./password-service:/app  # Ensure the app can read/write to the DB file
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
